[package]
name = "webrogue-launcher"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
winit = ["dep:winit"]

[dependencies]
wry = { workspace = true, default-features = true }
# tao = { workspace = true, default-features = true }
winit = { workspace = true, default-features = true, optional = true }
dpi = { workspace = true, default-features = false }
json-escape = { workspace = true }
webrogue-launcher-server-openapi = { workspace = true, default-features = true }
axum = { version = "0.8" }
axum-extra = { version = "0.10", features = ["cookie", "query"] }
http = { version = "*" }
async-trait = "0.1"
anyhow = { workspace = true }
tokio = { version = "1.0", features = ["full"] }
tower-service = "0.3"
bytes = "1.0"
tokio-stream = "0.1"
tower-http = { version = "*", features = ["cors"] }
lazy_static = "1.4"
futures-util = "0.3"

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"
