[package]
name = "webrogue-launcher"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]

[dependencies]
wry = { workspace = true, default-features = true }
# tao = { workspace = true, default-features = true }
winit = { workspace = true, default-features = true }
dpi = { workspace = true, default-features = false }
