[package]
name = "webrogue-launcher"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
winit = ["dep:winit"]

[dependencies]
wry = { workspace = true, default-features = true }
# tao = { workspace = true, default-features = true }
winit = { workspace = true, default-features = true, optional = true }
dpi = { workspace = true, default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"
