[package]
name = "webrogue-lld"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
link-llvm = []

[dependencies]
anyhow = { workspace = true }

[build-dependencies]
reqwest = { workspace = true, features = ["blocking"] }
