[versions]
agp = "8.12.3"
composeBom = "2024.04.01"

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
