[package]
name = "webrogue-hub-client"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
webrogue-hub-client-openapi = { workspace = true, default-features = false }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
webrtc = { workspace = true }
tokio = { version = "1.0", features = ["full"] }
base64 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }
postcard = { workspace = true, default-features = false, features = ['alloc', 'use-std'] }
webrogue-wrapp = { workspace = true }
blake3 = { workspace = true }
