[package]
name = "webrogue-wasip1"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]

[dependencies]
anyhow = { workspace = true }
webrogue-wrapp = { workspace = true }
wasi-common = { workspace = true, default-features = false, features = ["sync"] }
wiggle = { workspace = true, default-features = false }
async-trait = { workspace = true }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["pipe"] }

[target.'cfg(windows)'.dependencies]
io-extras = { workspace = true }

[dev-dependencies]
rand = { workspace = true, default-features = true, features = ["small_rng"] }
