[package]
name = "webrogue-gfxstream"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
cmake = ["dep:cmake", "dep:cc"]
cc = ["dep:cc"]

[dependencies]
lazy_static = { workspace = true }


[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, default-features = false, features = ["Win32_System_Memory", "Win32_System_SystemInformation"] }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, default-features = false, features = ["mm", "param"]}
libc = { workspace = true }

[build-dependencies]
cmake = { workspace = true, optional = true }
cc = { workspace = true, optional = true }
cfg_aliases = { workspace = true }
