[versions]
agp = "8.13.0"
kotlin = "2.2.21"
activityCompose = "1.11.0"
material = "1.13.0"
gamesActivity = "4.0.0"
appcompat = "1.7.1"
webkit = "1.14.0"

[libraries]
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-games-activity = { group = "androidx.games", name = "games-activity", version.ref = "gamesActivity" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
